/**
 * This code was generated by the Kepler Codegen tool.
 * 
 * It is provided as a starting template and can be modified.
 * 
 * @generated by GenerateModuleCpp.js
 */

#include "MoonlightVegaCore.h"

using namespace com::amazon::kepler::turbomodule;

namespace MoonlightVegaCoreTurboModule {

MoonlightVegaCore::MoonlightVegaCore() {}
MoonlightVegaCore::~MoonlightVegaCore() noexcept {};

com::amazon::kepler::turbomodule::JSObject MoonlightVegaCore::getCoreInfo() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

com::amazon::kepler::turbomodule::Promise MoonlightVegaCore::getServerInfo(std::string host, double port) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

} // namespace MoonlightVegaCoreTurboModule
