/**
 * This code was generated by the Kepler Codegen tool.
 * 
 * It is provided as a starting template and can be modified.
 * 
 * @generated by GenerateModuleH.js
 */

#include "generated/MoonlightVegaCoreSpec.h"

namespace MoonlightVegaCoreTurboModule {

class MoonlightVegaCore : public MoonlightVegaCoreSpec {
public:
  MoonlightVegaCore();
  ~MoonlightVegaCore() noexcept;

  com::amazon::kepler::turbomodule::JSObject getCoreInfo() override;
  com::amazon::kepler::turbomodule::Promise getServerInfo(std::string host, double port) override;
};

} // namespace MoonlightVegaCoreTurboModule
